/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Design System Colors (from Cognitive Talent OS) ──────────────
        'primary':                   '#0058be',
        'on-primary':                '#ffffff',
        'primary-container':         '#2170e4',
        'on-primary-container':      '#fefcff',
        'primary-fixed':             '#d8e2ff',
        'primary-fixed-dim':         '#adc6ff',
        'on-primary-fixed':          '#001a42',
        'on-primary-fixed-variant':  '#004395',
        'inverse-primary':           '#adc6ff',

        'secondary':                 '#006c49',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#6cf8bb',
        'on-secondary-container':    '#00714d',
        'secondary-fixed':           '#6ffbbe',
        'secondary-fixed-dim':       '#4edea3',
        'on-secondary-fixed':        '#002113',
        'on-secondary-fixed-variant':'#005236',

        'tertiary':                  '#4648d4',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#6063ee',
        'on-tertiary-container':     '#fffbff',
        'tertiary-fixed':            '#e1e0ff',
        'tertiary-fixed-dim':        '#c0c1ff',
        'on-tertiary-fixed':         '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',

        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',

        'surface':                   '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'surface-bright':            '#f8f9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant':           '#d3e4fe',
        'surface-tint':              '#005ac2',
        'on-surface':                '#0b1c30',
        'on-surface-variant':        '#424754',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',

        'outline':                   '#727785',
        'outline-variant':           '#c2c6d6',
        'background':                '#f8f9ff',
        'on-background':             '#0b1c30',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'mono-sm':     ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        'xs':  '4px',
        'sm':  '8px',
        'md':  '16px',
        'lg':  '24px',
        'xl':  '32px',
        'sidebar': '320px',
        'topbar': '64px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'sm':    '0.25rem',
        'md':    '0.75rem',
        'lg':    '1rem',
        'xl':    '1.5rem',
        'full':  '9999px',
      },
    },
  },
  plugins: [],
}
